[application]

[web.app]

# HTML title tag content
title = "CroftSoft Dioxus Demo"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []

# [web.wasm_opt]
# # The level wasm-opt should target. z is the smallest. 4 is the fastest.
# level = "4"

# [web.watcher]
# index_on_404 = true
# reload_html = true
# watch_path = ["assets", "src"]
